### ISSUE TITLE
model3v1 A mistake

### ISSUE THREAD

**Issue by damao666** [Sshanu/Relation-Extraction#18]
WARNING:tensorflow:From C:\Users\damao\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From D:/test/Relation-Classification-using-Bidirectional-LSTM-Tree-master/LSTM Seq and Tree/model3v1.py:440: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `argmax` instead
2019-07-05 22:47:07.901705: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-07-05 22:47:09.159543: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2019-07-05 22:47:09.160428: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1423] Adding visible gpu devices: 0
2019-07-05 22:47:10.446784: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-05 22:47:10.447031: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:917]      0 
2019-07-05 22:47:10.447155: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:930] 0:   N 
2019-07-05 22:47:10.448009: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3033 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "D:/test/Relation-Classification-using-Bidirectional-LSTM-Tree-master/LSTM Seq and Tree/model3v1.py", line 767, in <module>
    saver.restore(sess, model)
  File "C:\Users\damao\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 1769, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

Process finished with exit code 1

I am a new learner. Could you please tell me how to solve this problem?Thank you very much.

**Comment by radhikagupta6** [comment]
@damao666 I am facing the same save_path error with model3v2 can you help?
