### ISSUE TITLE
i run model3v1, but get run error like this:

### ISSUE THREAD

**Issue by tangm00** [Sshanu/Relation-Extraction#3]
INFO:tensorflow:Restoring parameters from None
Traceback (most recent call last):

  File "<ipython-input-1-440af85f342e>", line 1, in <module>
    runfile('D:/Download/chrome download/source codes/Information-Extraction-Chinese-master/RE_BGRU_2ATT/Relation-Classifition-Master-codes/LSTM Seq and Tree/model3v1.py', wdir='D:/Download/chrome download/source codes/Information-Extraction-Chinese-master/RE_BGRU_2ATT/Relation-Classifition-Master-codes/LSTM Seq and Tree')

  File "E:\DevelopTools\Anaconda3\envs\python35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "E:\DevelopTools\Anaconda3\envs\python35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Download/chrome download/source codes/Information-Extraction-Chinese-master/RE_BGRU_2ATT/Relation-Classifition-Master-codes/LSTM Seq and Tree/model3v1.py", line 725, in <module>
    saver.restore(sess, model)

  File "E:\DevelopTools\Anaconda3\envs\python35\lib\site-packages\tensorflow\python\training\saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})

  File "E:\DevelopTools\Anaconda3\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)

  File "E:\DevelopTools\Anaconda3\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)

  File "E:\DevelopTools\Anaconda3\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)

  File "E:\DevelopTools\Anaconda3\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)

  File "E:\DevelopTools\Anaconda3\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)

SystemError: <built-in function TF_Run> returned a result with an error set

**Comment by Sshanu** [comment]
You will get this error as you don't have the saved model for restoring it.

**Comment by tangm00** [comment]
thank u. i run it successfully.

**Comment by dyf0631** [comment]
How can change the code in model3v1.ipynb to slove the problem,I am a new comer,thanks!

**Comment by Sshanu** [comment]
just comment these lines:
model = tf.train.latest_checkpoint(model_dir)
saver.restore(sess, model)

These helps in restoring the model.

**Comment by dyf0631** [comment]
thank u. I just forget to mkdir.
 It is successful now .
